/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmazonSpApiRouteImport } from './routes/amazon-sp-api'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as OrderSyncRouteImport } from './routes/order-sync'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ReviewAnalyticsRouteImport } from './routes/review-analytics'
import { Route as SmartSchedulingRouteImport } from './routes/smart-scheduling'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs.$blogId'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonSpApiRoute = AmazonSpApiRouteImport.update({
  id: '/amazon-sp-api',
  path: '/amazon-sp-api',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSyncRoute = OrderSyncRouteImport.update({
  id: '/order-sync',
  path: '/order-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAnalyticsRoute = ReviewAnalyticsRouteImport.update({
  id: '/review-analytics',
  path: '/review-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSchedulingRoute = SmartSchedulingRouteImport.update({
  id: '/smart-scheduling',
  path: '/smart-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amazon-sp-api': typeof AmazonSpApiRoute
  '/guide': typeof GuideRoute
  '/order-sync': typeof OrderSyncRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/review-analytics': typeof ReviewAnalyticsRoute
  '/smart-scheduling': typeof SmartSchedulingRoute
  '/terms': typeof TermsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amazon-sp-api': typeof AmazonSpApiRoute
  '/guide': typeof GuideRoute
  '/order-sync': typeof OrderSyncRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/review-analytics': typeof ReviewAnalyticsRoute
  '/smart-scheduling': typeof SmartSchedulingRoute
  '/terms': typeof TermsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amazon-sp-api': typeof AmazonSpApiRoute
  '/guide': typeof GuideRoute
  '/order-sync': typeof OrderSyncRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/review-analytics': typeof ReviewAnalyticsRoute
  '/smart-scheduling': typeof SmartSchedulingRoute
  '/terms': typeof TermsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amazon-sp-api'
    | '/guide'
    | '/order-sync'
    | '/privacy'
    | '/refund'
    | '/review-analytics'
    | '/smart-scheduling'
    | '/terms'
    | '/blogs/$blogId'
    | '/payment/cancel'
    | '/payment/success'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amazon-sp-api'
    | '/guide'
    | '/order-sync'
    | '/privacy'
    | '/refund'
    | '/review-analytics'
    | '/smart-scheduling'
    | '/terms'
    | '/blogs/$blogId'
    | '/payment/cancel'
    | '/payment/success'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/amazon-sp-api'
    | '/guide'
    | '/order-sync'
    | '/privacy'
    | '/refund'
    | '/review-analytics'
    | '/smart-scheduling'
    | '/terms'
    | '/blogs/$blogId'
    | '/payment/cancel'
    | '/payment/success'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmazonSpApiRoute: typeof AmazonSpApiRoute
  GuideRoute: typeof GuideRoute
  OrderSyncRoute: typeof OrderSyncRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ReviewAnalyticsRoute: typeof ReviewAnalyticsRoute
  SmartSchedulingRoute: typeof SmartSchedulingRoute
  TermsRoute: typeof TermsRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon-sp-api': {
      id: '/amazon-sp-api'
      path: '/amazon-sp-api'
      fullPath: '/amazon-sp-api'
      preLoaderRoute: typeof AmazonSpApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-sync': {
      id: '/order-sync'
      path: '/order-sync'
      fullPath: '/order-sync'
      preLoaderRoute: typeof OrderSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-analytics': {
      id: '/review-analytics'
      path: '/review-analytics'
      fullPath: '/review-analytics'
      preLoaderRoute: typeof ReviewAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-scheduling': {
      id: '/smart-scheduling'
      path: '/smart-scheduling'
      fullPath: '/smart-scheduling'
      preLoaderRoute: typeof SmartSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmazonSpApiRoute: AmazonSpApiRoute,
  GuideRoute: GuideRoute,
  OrderSyncRoute: OrderSyncRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ReviewAnalyticsRoute: ReviewAnalyticsRoute,
  SmartSchedulingRoute: SmartSchedulingRoute,
  TermsRoute: TermsRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
